### ISSUE TITLE
making a RSS feed using PicoRobots

### ISSUE THREAD

**Issue by stefanocpp** [PhrozenByte/pico-robots#1]
Hi, thanks for the awesome work you're doing on Pico 2.0

Am I wrong or this plugin could be used to make a RSS feed using a `feed.twig` template akin to this:
> `PicoRobots` uses the `theme/sitemap.twig` template to create the contents of `sitemap.xml`. If you want to add some custom logic to your `sitemap.xml`, simply add a `sitemap.twig` to your theme and use `PicoRobot`'s `theme/sitemap.twig` as a starting point. Pico will automatically use your theme's `sitemap.twig` rather than PicoRobot's default one.

putting the logics necessary to produce a valid `feed.xml` file?

thank you

**Comment by PhrozenByte** [comment]
The logic of a `PicoFeed` plugin is basically the same as of `PicoRobots`, however, you can't use `PicoRobots` to build a RSS feed. A official RSS feed plugin is planned, but the website updates necessary for the release of Pico 2.0 currently have priority. However, you can still create a `feed.twig` template that produces a RSS feed and use e.g. `.htaccess` rules to change the response's Content-type to `application/rss+xml`. Also see the "RSS Feed Generation" section on http://picocms.org/cookbook/

**Comment by stefanocpp** [comment]
Thank you very much, I didn't even know that section of the website existed!
