### ISSUE TITLE
Update installation instruction

### ISSUE THREAD

**Issue by edison23** [PhrozenByte/pico-robots#2]
Please state clearly in the installation instructions that the `theme` directory needs to be _in the same directory_ as the `PicoRobots.php` file. The directory isn't mentioned at all, so when the plugin didn't work, I put the files into my own theme's directory. Only the PHP error log directed me as to where this plugin's `theme` directory is expected. 

Put the instructions to Readme.md > Install > the section that starts with "If you're rather using one of [Pico's pre-built release packages](https://github.com/picocms/Pico/releases/latest),". 

Thank you very much.

**Comment by PhrozenByte** [comment]
Valid point. You wanna open a PR to add these instructions?

By the way, you actually weren't wrong with your idea to add the Twig templates to your theme: This is indeed possible. It allows you to overwrite the plugin's templates in your theme without the need to fiddle around with the plugin's files. However, you'd still need the directory in the plugin's directory, i.e. both then. You wanna add this to the `README.md` too?

**Comment by edison23** [comment]
Thanks for the confirmation and additional details, and sorry for the late reply. Here's the PR with the fix: 3a45e31417ed16c0e058406de8b676f51acd1ee7

**Comment by edison23** [comment]
> Thanks for the confirmation and additional details, and sorry for the late reply. Here's the PR with the fix: [3a45e31](https://github.com/PhrozenByte/pico-robots/commit/3a45e31417ed16c0e058406de8b676f51acd1ee7)

Sorry, I screwed up and linked my own fork. This is the PR: https://github.com/PhrozenByte/pico-robots/pull/3
